// const BaseURL ='http://180.211.96.179/api/';
const env = 'stage';
const BaseURL =
  env == 'stage'
    ? 'http://94.237.13.69:8080/api/'
    : 'http://94.237.13.69:8080/api/';

export default Contstant = {
  loginURL: BaseURL + 'login',
  registerURL: BaseURL + 'register',
  logoutURL: BaseURL + 'logout',
  countriesURL: BaseURL + 'countries',
  stateURL: BaseURL + 'getcountry_state/',
  cityURL: BaseURL + 'getstate_city/',
  inviteURL: BaseURL + 'users',
  foodtypeURL: BaseURL + 'foodtypes',
  addDriveURL: BaseURL + 'add-drive',
  completedDriveURL: BaseURL + 'completed-drives',
  allDriveURL: BaseURL + 'drives',
  recentRobinsURL: BaseURL + 'recently-added/',
  zoneURL: BaseURL + 'getcity_zone/',
  profileURL: BaseURL + 'my-profile',
  dashboradCountURL: BaseURL + 'food-donation-drives',
  robinRequestURL: BaseURL + 'robin-requests',
  nearbyZoneURL: BaseURL + 'nearbyzone',
  overallSnapShorURL: BaseURL + 'overall-snapshort',
  zoneSelectionURL: BaseURL + 'drives-statistics',
  driveListOnZoneURL: BaseURL + 'drive-list-on-zone',
  totalDriveURL: BaseURL + 'overrall-sanpshort-statistics',
  topRobinsURL: BaseURL + 'top-robins',
  myDrivesURL: BaseURL + 'mydrives',
  startMyDriveURL: BaseURL + 'start-my-drive',
  endDriveURL: BaseURL + 'complete-my-drive',
  singleDriveURL: BaseURL + 'drive',
  achivementsURL: BaseURL + 'achievements',
  upcomingDriveURL: BaseURL + 'upcoming-drive',
  upcomingDriveDetailURL: BaseURL + 'upcoming-drive-detail',
  foodDonationDriveURL: BaseURL + 'next-food-donation-drive',
  currentDriveURL: BaseURL + 'my-currant-drive',
  currentDriveDetailURL: BaseURL + 'my-currant-drive-detail',
  completeCurrentDriveURL: BaseURL + 'complete-currant-drive',
  completeDriveDetailURL: BaseURL + 'complete-drive-detail',
  cancelDriveReasonsURL: BaseURL + 'cancle-drive-reasons',
  removeDriveRobinURL: BaseURL + 'remove-robin',
  cancelDriveURL: BaseURL + 'cancle-drive',
  notificationURL: BaseURL + 'notifications',
  joinStatusURL: BaseURL + 'join-status',
  joinDriveURL: BaseURL + 'join-drive',
  requestedDriveURL: BaseURL + 'requested_drives',
  driveAcceptURL: BaseURL + 'drive-accept',
  driveRejectURL: BaseURL + 'drive-reject',
  donerListURL: BaseURL + 'doner-listing',
  conformationDrivesURL: BaseURL + 'conformation-drives',
  forgotPasswordURL: BaseURL + 'forgot_password',
  otpVerificationURL: BaseURL + 'otp-verificcation',
  resetPasswordURL: BaseURL + 'new_password',
  cmsURL: BaseURL + 'cms',
  deleteImageDriveURL: BaseURL + 'delete-image-drive',
  joinReasonURL: BaseURL + 'join-drive-reasons',
  uploadImageURL: BaseURL + 'image_upload',
  nextFoodDonationDriveURL: BaseURL + 'next-foodation-drives',
  tokenRegisterURL: BaseURL + 'token_register',
};
